nelmio_api_doc:
    documentation:
        info:
            title: Log parser test task
            description: Rightmart test task
            version: 1.0.0
    areas:
        path_patterns:
            - ^/ # Accept all routes
